FROM apache/spark:3.5.1
USER root
WORKDIR /opt/spark/app

# Transform only interacts with S3 storage files (No Kafka jars needed)
ADD --chmod=644 https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar /opt/spark/jars/
ADD --chmod=644 https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar /opt/spark/jars/

COPY process/transform/src/ ./src/
USER spark

CMD ["/opt/spark/bin/spark-submit", \
     "--conf", "spark.driver.extraJavaOptions=-Duser.home=/tmp", \
     "./src/transform_job.py"]